"""More than words (G5b) — le même mécanisme, au-delà du texte.

Insertion draft des formations (planche drafts2 ``flux=multimodal``, NG
2026-09-01) : LE trou du deck d'avant — tout le fil parlait texte, or
« génératif » écrit AUSSI les images, la musique et les voix. Une slide, un
message : le même « prédire le prochain morceau », appliqué à d'autres
matières. La vidéo n'est pas ici : elle est le crescendo de la slide
suivante (2023 → 2025).

Retouche NG (2026-09-02, capture : les cartes Music/Voice passaient sous le
pli) : les cartes n'affichent PLUS ni média ni sous-titre — une icône et un
mot, au plus gros, les quatre cartes tiennent dans la fenêtre. Les PREUVES
(les visuels de ce deck, la chanson Suno 2024 « L'Intelligence
Artificielle », le podcast NotebookLM de 9 minutes) sont racontées au
panneau ℹ️ et portées par l'orateur ; les captures restent versionnées sous
``static/images/trainings/`` (le backup « podcast » du plan Mistral s'en
sert).

Le FAIT vit ici (règle NG 2026-08-18) : les noms d'outils et les dates
vivent dans le panneau, jamais projetés en gros — la slide dit le mécanisme,
pas un catalogue de produits. Aucune affirmation sourcée.

SPEAKER NOTES:
Ninety seconds. Sweep the four cards left to right, one sentence each: the
text you have seen; the images — every visual of this deck, generated; a
French pop song about AI, generated; a nine-minute podcast about a course,
generated from the notes. Land on the punch: ONE mechanism — predict the
next piece, whatever the material. Tease: « and video? Next slide. »
"""
# @guideline: postair-minimal

from custom.styles import Styles as s
from postair_lang import T, TF
from shared_widgets import st_info_tooltip
from streamtex import *
from streamtex.enums import Tags as t


class BlockStyles:
    title = s.project.titles.slide_title + s.center_txt
    icon = s.project.titles.subtitle + s.center_txt
    label = s.project.body.bullet + s.center_txt + s.bold
    punch = s.project.titles.subtitle + s.project.colors.amber + s.center_txt


bs = BlockStyles

#: Réglages datés (retouche NG 2026-09-02 : icône + mot, ajustés au SIMPLE
#: ``st_zoom`` — consigne NG : pas de mécanique lourde, deux nombres à
#: tourner). Contrainte : titre + DEUX rangées de cartes sous le pli —
#: v1 300/220 débordait (capture NG), redescendu à l'œil le même jour.
TUNING = {"icon_zoom": 170, "label_zoom": 160, "card_air_vh": 0.2}

# ── Les quatre matières — une icône, un mot ─────────────────────────────────
_CARDS = [
    {"icon": "✍️", "label": {"en": "Text", "fr": "Texte"}},
    {"icon": "🖼️", "label": {"en": "Image", "fr": "Image"}},
    {"icon": "🎵", "label": {"en": "Music", "fr": "Musique"}},
    {"icon": "🎙️", "label": {"en": "Voice", "fr": "Voix"}},
]

_MARKER = {"en": "Multimodal", "fr": "Multimodal"}
_TITLE = {"en": ("The same trick, ", (s.project.titles.keyword, "beyond words")), "fr": ("La même astuce, ", (s.project.titles.keyword, "au-delà des mots"))}
_PUNCH = {"en": ("next token · next pixel · next note · next sample",
                 "ONE mechanism"), "fr": ("prochain token · prochain pixel · prochaine note · prochain échantillon", "UN seul mécanisme")}

_TIP_TITLE = {"en": "The proofs, precisely", "fr": "Les preuves, précisément"}
_TOOLTIP = [
    ({"en": "Images", "fr": "Les images"},
     {"en": ("Every illustration of this deck was generated for it (gpt-image, "
             "2026) and carries the AI mark — the small badge in the corner."), "fr": "Chaque illustration de ce document a été générée pour lui (gpt-image, 2026) et porte la marque IA — le petit badge dans le coin."}),
    ({"en": "Music", "fr": "La musique"},
     {"en": ("« L'Intelligence Artificielle », melodic chanson pop — generated "
             "with Suno (March 2024) for the AISE trainings, lyrics included."), "fr": "« L’Intelligence Artificielle », chanson pop mélodique — générée avec Suno (mars 2024) pour les formations AISE, paroles comprises."}),
    ({"en": "Voice & podcast", "fr": "La voix & le podcast"},
     {"en": ("A nine-minute two-voice podcast generated by NotebookLM from "
             "course notes (2024) — the hosts do not exist."), "fr": "Un podcast de neuf minutes à deux voix, généré par NotebookLM à partir de notes de cours (2024) — les animateurs n’existent pas."}),
    ({"en": "And the rest", "fr": "Et le reste"},
     {"en": ("Speech-to-text (Whisper), code, molecules, video — the recipe "
             "generalises: encode the material as tokens, predict the next "
             "one. Video is the next slide."), "fr": "Transcription de la parole (Whisper), code, molécules, vidéo — la recette se généralise : encoder la matière en tokens, prédire le suivant. La vidéo, c’est la slide suivante."}),
]


def build(lang: str = "en", **_):
    st_marker(T(_MARKER, lang))
    with st_block(s.project.containers.page_fill_top):
        with st_grid(cols="92% 8%",
                     cell_styles=s.project.containers.grid_cell_centered) as g:
            with g.cell():
                st_write(bs.title, *TF(_TITLE, lang),
                         tag=t.div, toc_lvl="+1", label=T(_MARKER, lang))
            with g.cell():
                st_info_tooltip(
                    title=T(_TIP_TITLE, lang),
                    entries=[(T(h, lang), T(d, lang)) for h, d in _TOOLTIP],
                )
        st_space("v", "2vh")
        with st_grid(cols=s.project.grids.balanced(len(_CARDS)), gap="1.2vw",
                     grid_style=s.project.grids.stretch,
                     cell_styles=s.project.containers.grid_cell_centered) as g:
            # Icône + mot, au plus gros (retouche NG 2026-09-02) : ni média
            # ni sous-titre dans les cartes — les preuves (visuels du deck,
            # chanson Suno, podcast NotebookLM) sont racontées au panneau.
            for c in _CARDS:
                with g.cell(), st_block(s.project.cards.blue):
                    st_space("v", f"{TUNING['card_air_vh']}vh")
                    with st_zoom(TUNING["icon_zoom"]):
                        st_write(bs.icon, c["icon"], tag=t.div)
                    st_space("v", "1vh")
                    with st_zoom(TUNING["label_zoom"]):
                        st_write(bs.label, T(c["label"], lang), tag=t.div)
                    st_space("v", f"{TUNING['card_air_vh']}vh")
        st_space("v", "4vh")
        with st_zoom(130):
            for line in T(_PUNCH, lang):
                st_write(bs.punch, line, tag=t.div)
