"""More than words (G5b) — le même mécanisme, au-delà du texte.

Insertion draft des formations (planche drafts2 ``flux=multimodal``, NG
2026-09-01) : LE trou du deck d'avant — tout le fil parlait texte, or
« génératif » écrit AUSSI les images, la musique et les voix. Une slide, un
message : le même « prédire le prochain morceau », appliqué à d'autres
matières. La vidéo n'est pas ici : elle est le crescendo de la slide
suivante (2023 → 2025).

Les preuves sont des ARTEFACTS des formations AISE de NG (réutilisation
autorisée 2026-09-01) : la chanson générée « L'Intelligence Artificielle »
(Suno, 2024) et le podcast généré depuis des notes de cours (NotebookLM,
9 minutes) — des captures d'interface, pas des images générées : pas de
pastille DD-35. La carte Image porte le héros de CE deck (généré par IA,
sidecar ``ai_generated``) : pastille DD-35 posée.

Le FAIT vit ici (règle NG 2026-08-18) : les noms d'outils et les dates
vivent dans le panneau, jamais projetés en gros — la slide dit le mécanisme,
pas un catalogue de produits. Aucune affirmation sourcée.

SPEAKER NOTES:
Ninety seconds. Sweep the four cards left to right, one sentence each: the
text you have seen; the images — every visual of this deck, generated; a
French pop song about AI, generated; a nine-minute podcast about a course,
generated from the notes. Land on the punch: ONE mechanism — predict the
next piece, whatever the material. Tease: « and video? Next slide. »
"""
# @guideline: postair-minimal

from custom.styles import Styles as s
from postair_lang import T, TF
from shared_widgets import st_info_tooltip
from streamtex import *
from streamtex.enums import Tags as t

from postair_pack.components.ai_mark import dd35_overlay


class BlockStyles:
    title = s.project.titles.slide_title + s.center_txt
    icon = s.project.titles.subtitle + s.center_txt
    label = s.project.body.bullet + s.center_txt + s.bold
    line = s.project.body.caption + s.center_txt
    punch = s.project.titles.subtitle + s.project.colors.amber + s.center_txt


bs = BlockStyles

#: Réglages datés (2026-09-01) : hauteur des médias de carte.
TUNING = {"card_media_vh": 26}

# ── Les quatre matières — icône, étiquette, preuve, une ligne ───────────────
#: ``uri`` vide = carte sans média (le texte se prouve tout seul : le deck).
#: ``ratio`` mesuré Pillow sur le fichier versionné ; ``ai`` = pastille DD-35.
_CARDS = [
    {
        "icon": "✍️", "label": {"en": "Text"},
        "uri": "", "ratio": 1.0, "ai": False,
        "line": {"en": "next token — you just played it"},
    },
    {
        "icon": "🖼️", "label": {"en": "Image"},
        "uri": "images/managed/genai_hero_sq.webp", "ratio": 1.0, "ai": True,
        "line": {"en": "every visual of this deck"},
    },
    {
        "icon": "🎵", "label": {"en": "Music"},
        "uri": "images/trainings/multimodal_music.png", "ratio": 0.739, "ai": False,
        "line": {"en": "a generated French chanson (2024)"},
    },
    {
        "icon": "🎙️", "label": {"en": "Voice"},
        "uri": "images/trainings/multimodal_podcast.png", "ratio": 2.519, "ai": False,
        "line": {"en": "a 9-minute podcast, from course notes"},
    },
]

_MARKER = {"en": "Multimodal"}
_TITLE = {"en": ("The same trick, ", (s.project.titles.keyword, "beyond words"))}
_PUNCH = {"en": ("next token · next pixel · next note · next sample",
                 "ONE mechanism")}

_TIP_TITLE = {"en": "The proofs, precisely"}
_TOOLTIP = [
    ({"en": "Images"},
     {"en": ("Every illustration of this deck was generated for it (gpt-image, "
             "2026) and carries the AI mark — the small badge in the corner.")}),
    ({"en": "Music"},
     {"en": ("« L'Intelligence Artificielle », melodic chanson pop — generated "
             "with Suno (March 2024) for the AISE trainings, lyrics included.")}),
    ({"en": "Voice & podcast"},
     {"en": ("A nine-minute two-voice podcast generated by NotebookLM from "
             "course notes (2024) — the hosts do not exist.")}),
    ({"en": "And the rest"},
     {"en": ("Speech-to-text (Whisper), code, molecules, video — the recipe "
             "generalises: encode the material as tokens, predict the next "
             "one. Video is the next slide.")}),
]


def build(lang: str = "en", **_):
    st_marker(T(_MARKER, lang))
    with st_block(s.project.containers.page_fill_top):
        with st_grid(cols="92% 8%",
                     cell_styles=s.project.containers.grid_cell_centered) as g:
            with g.cell():
                st_write(bs.title, *TF(_TITLE, lang),
                         tag=t.div, toc_lvl="+1", label=T(_MARKER, lang))
            with g.cell():
                st_info_tooltip(
                    title=T(_TIP_TITLE, lang),
                    entries=[(T(h, lang), T(d, lang)) for h, d in _TOOLTIP],
                )
        st_space("v", s.project.spacing.title_gap)
        with st_grid(cols=s.project.grids.balanced(len(_CARDS)), gap="1.2vw",
                     grid_style=s.project.grids.stretch,
                     cell_styles=s.project.containers.grid_cell_centered) as g:
            for c in _CARDS:
                with g.cell(), st_block(s.project.cards.blue):
                    st_write(bs.icon, c["icon"], tag=t.div)
                    st_write(bs.label, T(c["label"], lang), tag=t.div)
                    st_space("v", "1.5vh")
                    if c["uri"]:
                        with st_block(s.project.containers.media_stage(
                                c["ratio"], TUNING["card_media_vh"])):
                            st_image(s.project.cards.media_center, uri=c["uri"],
                                     alt=T(c["line"], lang),
                                     overlay=dd35_overlay(c["ai"]))
                    else:
                        # La carte Texte n'a pas de média : sa preuve est la
                        # phrase à trou jouée deux slides plus tôt.
                        st_space("v", "4vh")
                        with st_zoom(160):
                            st_write(bs.icon, "«", " ____ ", "»", tag=t.div)
                        st_space("v", "4vh")
                    st_space("v", "1.5vh")
                    st_write(bs.line, T(c["line"], lang), tag=t.div)
        st_space("v", "4vh")
        with st_zoom(130):
            for line in T(_PUNCH, lang):
                st_write(bs.punch, line, tag=t.div)
