"""Two years of generated video (G5c) — 2023 face au 2025, côte à côte.

Insertion draft des formations (planche drafts2 ``flux=chronovideo``, NG
2026-09-01) : le rythme du progrès rendu VISCÉRAL — aucun chiffre de Scale ne
dit ça aussi fort. À gauche, une génération de 2023 : un visage qui se
déforme, quelques secondes, des artefacts partout. À droite, mai 2025 : « un
caméléon employé de bureau débordé » — une phrase, et la scène existe,
photoréaliste. Les deux clips sont des PRODUCTIONS des formations AISE de NG
(réutilisation autorisée 2026-09-01), convertis des GIF d'origine en mp4
(``static/video/videogen-*.mp4``, versionnés — exception assumée du dépôt,
même geste que ``transformers-01.mp4``).

Autoplay muet en boucle (le geste de l'écran d'attente d'opening) : les
clips tournent dès l'arrivée sur la slide, aucun son, aucun clic — c'est une
image qui bouge, pas un film à lancer. Pastille DD-35 sur les deux
(contenus générés par IA).

Le FAIT vit ici (règle NG 2026-08-18) : les années (2023, mai 2025) et les
outils (essais précoces ; Veo) — dits dans le panneau, jamais projetés en
gros. Annonces d'outillage, pas d'affirmation scientifique : pas de citekey
(même statut que le jalon « 2026 agents » de la frise).

SPEAKER NOTES:
One minute, mostly silent — let the loops speak. Point left: 2023, this was
the state of the art, seconds of a melting face. Point right: 2025, one
sentence in, this out. Then the only line that matters: this gap is TWO
YEARS — the same two years as the scale curve you just saw. If someone asks
« so are videos still trustable? »: that is exactly where the deck goes next
(capabilities, then the other side).
"""
# @guideline: postair-minimal

from pathlib import Path

from custom.styles import Styles as s
from postair_lang import T, TF
from shared_widgets import st_info_tooltip
from streamtex import *
from streamtex.enums import Tags as t

from postair_pack.components.ai_mark import ai_marked

#: Résolus depuis le fichier, jamais du répertoire courant (piège du lanceur).
_VIDEO_DIR = Path(__file__).parent.parent / "static" / "video"

#: Mesuré ffprobe (2026-09-01) : 2023 = 480×270 (17 s), 2025 = 960×540 (31 s).
_CLIPS = [
    {
        "file": "videogen-2023.mp4",
        "year": {"en": "2023"},
        "line": {"en": "a face · seconds · artefacts"},
    },
    {
        "file": "videogen-2025.mp4",
        "year": {"en": "2025"},
        "line": {"en": "« an overwhelmed chameleon office worker » — one sentence"},
    },
]

_MARKER = {"en": "2023 → 2025"}
_TITLE = {"en": ("Two years of ", (s.project.titles.keyword, "generated video"))}
_PUNCH = {"en": ("the SAME two years as the scale curve",)}

_TIP_TITLE = {"en": "The two clips, precisely"}
_TOOLTIP = [
    ({"en": "Left — 2023"},
     {"en": ("An early text-to-video attempt from the AISE trainings: low "
             "resolution, a morphing face, visible artefacts — the honest "
             "state of the art of that year.")}),
    ({"en": "Right — May 2025"},
     {"en": ("The chameleon office worker, generated by Veo from a one-"
             "sentence prompt written for the trainings (FR and EN versions "
             "exist) — photoreal fur, lighting, motion.")}),
    ({"en": "Why it matters here"},
     {"en": ("This is the scale slide made visible: same mechanism, two years "
             "of data + compute — and a reason to trust your EYES a bit less "
             "(the deepfake question comes back in the limits).")}),
]


class BlockStyles:
    title = s.project.titles.slide_title + s.center_txt
    year = s.project.titles.subtitle + s.project.colors.keyword + s.center_txt + s.bold
    line = s.project.body.caption + s.center_txt
    punch = s.project.titles.subtitle + s.project.colors.amber + s.center_txt


bs = BlockStyles


def build(lang: str = "en", **_):
    st_marker(T(_MARKER, lang))
    with st_block(s.project.containers.page_fill_top):
        with st_grid(cols="92% 8%",
                     cell_styles=s.project.containers.grid_cell_centered) as g:
            with g.cell():
                st_write(bs.title, *TF(_TITLE, lang),
                         tag=t.div, toc_lvl="+1", label=T(_MARKER, lang))
            with g.cell():
                st_info_tooltip(
                    title=T(_TIP_TITLE, lang),
                    entries=[(T(h, lang), T(d, lang)) for h, d in _TOOLTIP],
                )
        st_space("v", s.project.spacing.title_gap)
        with st_grid(cols="50% 50%", gap="1.5vw",
                     cell_styles=s.project.containers.grid_cell_centered) as g:
            for clip in _CLIPS:
                with g.cell():
                    with st_zoom(140):
                        st_write(bs.year, T(clip["year"], lang), tag=t.div)
                    st_space("v", "1vh")
                    # 16/9 pour les deux fichiers ; la scène borne par la
                    # hauteur ET la cellule (R4d).
                    with st_block(s.project.containers.media_stage(16 / 9, 52)):
                        with ai_marked(fit=False, top=True):
                            st_video(str(_VIDEO_DIR / clip["file"]),
                                     loop=True, autoplay=True)
                    st_space("v", "1vh")
                    st_write(bs.line, T(clip["line"], lang), tag=t.div)
        st_space("v", "3vh")
        with st_zoom(130):
            for line in T(_PUNCH, lang):
                st_write(bs.punch, line, tag=t.div)
